mysql:
  host: localhost
  port: 3306
  user: root
  password: password
  database: mydatabase

redis:
  host: localhost
  port: 6379
  password: password
  db: 0

mongo:
  uri: mongodb://localhost:27017
  database: mydatabase

kafka:
  brokers:
    - localhost:9092
  topics:
    - mytopic

logging:
  level: INFO